import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // Book sidebar for the main course content
  bookSidebar: [
    {
      type: 'category',
      label: 'Course',
      items: [
        {
          type: 'category',
          label: '01 - Introduction',
          items: [
            'book/introduction/introduction-to-physical-ai',
            'book/introduction/what-is-robotics',
            'book/introduction/history-of-robotics',
            'book/introduction/robotics-domains',
            'book/introduction/robot-components',
            'book/introduction/ethics-and-society',
            'book/introduction/future-of-robotics',
          ],
        },
        {
          type: 'category',
          label: '02 - Electronics',
          items: [
            {type: 'autogenerated', dirName: 'book/02-electronics'},
          ],
        },
        {
          type: 'category',
          label: '03 - Programming',
          items: [
            {type: 'autogenerated', dirName: 'book/03-programming'},
          ],
        },
        {
          type: 'category',
          label: '04 - Sensors',
          items: [
            {type: 'autogenerated', dirName: 'book/04-sensors'},
          ],
        },
        {
          type: 'category',
          label: '05 - Microcontrollers',
          items: [
            {type: 'autogenerated', dirName: 'book/05-microcontrollers'},
          ],
        },
        {
          type: 'category',
          label: '06 - Algorithms',
          items: [
            {type: 'autogenerated', dirName: 'book/06-algorithms'},
          ],
        },
        {
          type: 'category',
          label: '07 - Computer Vision',
          items: [
            {type: 'autogenerated', dirName: 'book/07-computer-vision'},
          ],
        },
        {
          type: 'category',
          label: '08 - AI & Robotics',
          items: [
            {type: 'autogenerated', dirName: 'book/08-ai-robotics'},
          ],
        },
        {
          type: 'category',
          label: '09 - Projects',
          items: [
            {type: 'autogenerated', dirName: 'book/09-projects'},
          ],
        },
        {
          type: 'category',
          label: '10 - Hackathon',
          items: [
            {type: 'autogenerated', dirName: 'book/10-hackathon-q4'},
          ],
        },
        {
          type: 'category',
          label: '11 - Appendix',
          items: [
            {type: 'autogenerated', dirName: 'book/11-appendix'},
          ],
        },
      ],
    },
  ],

  // Chapters sidebar for supplementary content
  chaptersSidebar: [
    {
      type: 'category',
      label: 'Learning Resources',
      items: [
        'chapters/getting-started',
        'chapters/intro',
        'chapters/personalization',
        'chapters/rag-chatbot',
        'chapters/urdu-translation',
      ],
    },
  ],
};

export default sidebars;
