module.exports = {
  docsSidebar: [
    {
      type: 'category',
      label: 'Robotics Course',
      items: [
        {
          type: 'autogenerated',
          dirName: '.',
        },
      ],
    },
  ],
};
